use anydesk_pivot_detector::models::alert::{Alert, AlertSeverity};
use chrono::Utc;
use serde_json::json;
use uuid::Uuid;

pub fn create_alert(severity: AlertSeverity, title: &str) -> Alert {
    Alert {
        id: Uuid::new_v4().to_string(),
        timestamp: Utc::now(),
        severity,
        title: title.to_string(),
        description: "Generated by test factory".to_string(),
        source_module: "TestFactory".to_string(),
        evidence: json!({}),
    }
}

pub fn create_low_alert() -> Alert {
    create_alert(AlertSeverity::Low, "Low Risk Event")
}

pub fn create_high_alert() -> Alert {
    create_alert(AlertSeverity::High, "High Risk Event")
}
